# Generated by Django 4.0.4 on 2022-08-10 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_status', models.CharField(max_length=200)),
                ('email_score', models.IntegerField(verbose_name='Email Score')),
                ('valid_email', models.BooleanField(default=True)),
                ('fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
